# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSWithReactNative' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSWithReactNative
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]


end
